name = "testgen"
engineVersion = "v1.0.0-beta.9"

[runtime]
  source = "dang"

[[dependencies]]
  name = "go"
  source = "github.com/dagger/go@main"
  pin = "548de867d65d3074c5730c70f317094f167709c7"
